# Generated by Django 6.1 on 2026-08-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0002_userpresence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpresence',
            options={'verbose_name': 'User Presence', 'verbose_name_plural': 'User Presence'},
        ),
    ]
