# Generated by Django 6.1 on 2026-09-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0004_bankaccount_wallet_wallet_balance_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='direct_pair_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('conversation_type', 'direct')), fields=('conversation_type', 'direct_pair_key'), name='unique_direct_conversation_per_pair'),
        ),
    ]
