# Generated by Django 6.1 on 2026-09-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0006_alter_conversation_avatar_alter_message_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('flutterwave_airtime_biller', models.CharField(max_length=100)),
                ('flutterwave_data_biller', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='networks/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
