# Generated by Django 6.1 on 2026-09-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0007_networkprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pheraltransaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('top_up', 'Top Up'), ('withdrawal', 'Withdrawal'), ('fx', 'Currency Conversion'), ('group_transfer', 'Group Transfer'), ('hire_payment', 'Hire Payment'), ('refund', 'Refund'), ('airtime', 'Airtime'), ('data', 'Data')], max_length=30),
        ),
    ]
