# Generated by Django 6.1 on 2026-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0008_alter_pheraltransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkprovider',
            name='flutterwave_airtime_biller_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='networkprovider',
            name='flutterwave_data_biller_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='flutterwave_airtime_biller',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkprovider',
            name='flutterwave_data_biller',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
