# Generated by Django 6.1 on 2026-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0009_networkprovider_flutterwave_airtime_biller_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
