# Generated by Django 6.1 on 2026-09-26 11:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pheral.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0012_virtualaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('lifetime_purchased', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('lifetime_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenZBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(default=pheral.models.generate_genz_reference, editable=False, max_length=30, unique=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genz_badges', to='pheral.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genz_badge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PheralSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('pro', 'Pheral Pro')], default='pro', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pheral_subscriptions', to='pheral.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pheral_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=pheral.models.generate_revenue_reference, editable=False, max_length=30, unique=True)),
                ('revenue_type', models.CharField(choices=[('payment_fee', 'Payment Fee'), ('withdrawal_fee', 'Withdrawal Fee'), ('fx_margin', 'FX Margin'), ('card_fee', 'Virtual Card Fee'), ('bill_commission', 'Bill Commission'), ('job_fee', 'Job Fee'), ('sponsored_post', 'Sponsored Post'), ('genz_badge', 'GenZ Badge'), ('pro_subscription', 'Pheral Pro'), ('ai', 'AI'), ('float', 'Float Income'), ('other', 'Other')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_records', to='pheral.currency')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_records', to='pheral.pheraltransaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsoredPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_posts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_posts', to='pheral.currency')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship', to='pheral.post')),
            ],
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('credits_used', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_ai_usage_per_day')],
            },
        ),
    ]
