# Generated by Django 6.1 on 2026-09-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0013_aicreditbalance_genzbadge_pheralsubscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='paystack_recipient_code',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='flutterwave_recipient_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
