# Generated by Django 6.1 on 2026-09-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0014_remove_bankaccount_paystack_recipient_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkprovider',
            name='flutterwave_airtime_item_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
