# Generated by Django 6.1 on 2026-10-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheral', '0015_networkprovider_flutterwave_airtime_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=254, unique=True)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('invited', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
